version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    env_file: 
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - .env

volumes:
  postgres_data:
